### ISSUE TITLE
The v0.10.0 release version has a prefix in the tag and style different from other tags

### ISSUE THREAD

**Issue by judaew** [git-chglog/git-chglog#95]
## Expected Behavior

Tag `v0.10.0` has prefix "v" in name.

## Actual Behavior

Other tags don't have this prefix.

## Steps to Reproduce (including precondition)

1. Open repo git-chglog;
2. Go to tags or releases page;
3. Pay attention to tags `v0.10.0` and `0.9.1`.

## Screenshot on This Problem (if possible)

<img width="396" alt="Screen Shot 2021-02-13 at 14 54 00" src="https://user-images.githubusercontent.com/41125715/107850678-d6f55f80-6e0c-11eb-9a7f-68e225742c13.png">

## Your Environment

- ~~OS:~~
- git-chglog version: 0.10.0

**Comment by mavogel** [comment]
We did this on purpose because go modules start with a `v` prefix (see https://github.com/git-chglog/git-chglog/issues/88#issuecomment-760996234) as part of the new release process
We announced the BC in the [CHANGELOG](https://github.com/git-chglog/git-chglog/blob/master/CHANGELOG.md#breaking-change). 

Sorry for the inconvenience but as we are still pre `v1.0.0` we sometimes need to add those BC. But we try to keep then to a minimum.

**Comment by judaew** [comment]
I apologize for missing this point in the changelog. Thanks for the detailed answer.

**Comment by mavogel** [comment]
No worries @judaew :) happy to help and clarify. And feel free to contribute here as well

**Comment by clok** [comment]
Noting here that we will need to update the asdf plugin https://github.com/GoodwayGroup/asdf-git-chglog/issues/1

**Comment by clok** [comment]
https://github.com/GoodwayGroup/asdf-git-chglog/pull/2
